# Generated by Django 3.0.7 on 2020-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Названия места')),
                ('images', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description_short', models.CharField(max_length=300, verbose_name='Краткое описания')),
                ('description_long', models.TextField(verbose_name='Полное описания')),
                ('long', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
