# Generated by Django 3.0.7 on 2020-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_auto_20200604_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimages',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
