# Generated by Django 3.0.7 on 2020-06-06 12:31

import afisha.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_placeimages_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimages',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='position',
            field=models.IntegerField(default=afisha.models.get_image_position, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
