# Generated by Django 3.0.7 on 2020-06-06 17:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0004_auto_20200606_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='afisha.Places', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название места'),
        ),
    ]
