# Generated by Django 3.0.7 on 2020-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_auto_20200606_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimages',
            options={'ordering': ['position'], 'verbose_name': 'Изображениe', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['title'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
